### PR TITLE
Build the Debian Desktop AMI on a Graviton (ARM64) instance

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request modifies the Packer code to build the Debian Desktop AMI on a Graviton (ARM64) instance.

See also cisagov/cool-assessment-terraform#244.

## 💭 Motivation and context ##

Running the AMI on Graviton should be cheaper and better for the environment.

## 🧪 Testing ##

All automated tests pass.  I also built a staging AMI with these changes and verified that it functions as expected.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] All new and existing tests pass.
- [x] Build and test a staging AMI with these changes.

## ✅ Pre-merge checklist ##

- [x] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Exciting times!

**Comment by dv4harr10** [comment]
Hi Team @all , In the README.md file the link in this sentence returns a 404 error: "If you have appropriate permissions for the repository you can view existing secrets on the 'appropriate page' in the repository's settings. The link is pointing to the following "github.com/cisagov/debian-packer/settings/secrets/actions

**Comment by jsf9k** [comment]
> Hi Team @ALL , In the README.md file the link in this sentence returns a 404 error: "If you have appropriate permissions for the repository you can view existing secrets on the 'appropriate page' in the repository's settings. The link is pointing to the following "github.com/cisagov/debian-packer/settings/secrets/actions

@dv4harr10 - I think you get a 404 just because you lack the permission to view those settings.  The link you listed works fine on my end.

**Review by dv4harr10 — APPROVED** [review]

**Review by mcdonnnj — COMMENTED** [review]
I just wanted to voice some hesitancy on wholesale switching to ARM on this image as opposed to building an AMI for both (AMD64 and ARM64) architectures.

**Comment by dav3r** [comment]
> I just wanted to voice some hesitancy on wholesale switching to ARM on this image as opposed to building an AMI for both (AMD64 and ARM64) architectures.

This AMI is not used very much at all.  The only environments where I see it being used are our sandbox for testing user access and a WAS/ZAP testing environment.  I think the risk of migrating wholesale to ARM is minimal here, but we can reach out to those WAS/ZAP users and find out if this will affect their work.

**Comment by dav3r** [comment]
> I think the risk of migrating wholesale to ARM is minimal here, but we can reach out to those WAS/ZAP users and find out if this will affect their work.

I emailed that team and will post an update here when we get more info.

**Comment by dav3r** [comment]
> > I think the risk of migrating wholesale to ARM is minimal here, but we can reach out to those WAS/ZAP users and find out if this will affect their work.
> 
> I emailed that team and will post an update here when we get more info.

The WAS team is no longer using that environment.  I'm not aware of anyone actively using this AMI at the moment, so the risk of moving it to ARM is very low.

**Comment by jsf9k** [comment]
> I just wanted to voice some hesitancy on wholesale switching to ARM on this image as opposed to building an AMI for both (AMD64 and ARM64) architectures.

Please see cisagov/skeleton-packer#355.  If that PR is preferred then I will close this one (as well as cisagov/samba-packer#48 and cisagov/terraformer-packer#54) and launch a [cisagov/skeleton-packer](https://github.com/cisagov/skeleton-packer) mini-Kraken.

**Comment by jsf9k** [comment]
Closed in favor of #64.

**Pull request closed without merging**
